"""Execute finalized AArch64 transport as Linux ELF through owned tools.

This is a transport/ABI regression, not a production TLS-startup or GC gate.
The assembly fixture supplies one thread's TLS and rewrites one registered
root. Its variadic call is independently laid out according to AAPCS64, rather
than relying on a caller and callee generated by the same emitter.
"""

import platform
import subprocess
import sys

import pytest

from pcc.backend import arm64_asm_driver, arm64_elf_driver
from pcc.backend.elf_x86_64 import (
    EM_AARCH64,
    STT_TLS,
    emit_relocatable,
    link_static_executable,
    parse_relocatable,
    parse_static_executable,
)
from pcc.backend.precise_stackmap import (
    ARCH_AARCH64,
    LOCATION_MANAGED,
    SAFEPOINT_CALL,
    decode_stack_map,
    function_id,
)
from pcc.backend.self_backend_aarch64_darwin import (
    emit_aarch64_darwin_asm,
    emit_aarch64_darwin_indexed_transport,
)
from pcc.backend.self_backend_parse import parse_self_backend_module


_LINUX_AARCH64 = (
    sys.platform == "linux"
    and platform.machine().lower() in ("aarch64", "arm64")
)

_IR = '''
target triple = "aarch64-unknown-linux-gnu"
@tls_init = thread_local global i64 37, align 8
@tls_zero = external thread_local global i64, align 8
@frame_map = internal constant i32 1
@old_storage = global [2 x i64] [i64 0, i64 111], align 8
@new_storage = global [2 x i64] [i64 0, i64 222], align 8
declare void @llvm.va_start.p0(ptr)
declare void @llvm.va_end.p0(ptr)
declare void @pcc_gc_frame_enter(ptr, ptr)
declare void @pcc_gc_frame_leave(ptr)
declare void @pcc_thread_safepoint()
declare i64 @peek(ptr)

define i32 @collect(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f, i64 %g, {i64, i64} %named, ...) {
entry:
  %ap = alloca {ptr, ptr, ptr, i32, i32}, align 8
  call void @llvm.va_start.p0(ptr %ap)
  %mixed = va_arg ptr %ap, {double, i64}
  %real = va_arg ptr %ap, double
  %integer = va_arg ptr %ap, i64
  %hfa = va_arg ptr %ap, {double, double}
  call void @llvm.va_end.p0(ptr %ap)
  %sum1 = add i64 %a, %b
  %sum2 = add i64 %sum1, %c
  %sum3 = add i64 %sum2, %d
  %sum4 = add i64 %sum3, %e
  %sum5 = add i64 %sum4, %f
  %sum6 = add i64 %sum5, %g
  %named_a = extractvalue {i64, i64} %named, 0
  %named_b = extractvalue {i64, i64} %named, 1
  %mixed_real = extractvalue {double, i64} %mixed, 0
  %mixed_integer = extractvalue {double, i64} %mixed, 1
  %hfa_a = extractvalue {double, double} %hfa, 0
  %hfa_b = extractvalue {double, double} %hfa, 1
  %bad_sum = icmp ne i64 %sum6, 28
  %bad_named_a = icmp ne i64 %named_a, 31
  %bad_named_b = icmp ne i64 %named_b, 32
  %bad_mixed_real = fcmp une double %mixed_real, 4.150000e+01
  %bad_mixed_integer = icmp ne i64 %mixed_integer, 42
  %bad_real = fcmp une double %real, 5.150000e+01
  %bad_integer = icmp ne i64 %integer, 61
  %bad_hfa_a = fcmp une double %hfa_a, 7.150000e+01
  %bad_hfa_b = fcmp une double %hfa_b, 7.250000e+01
  %bad1 = or i1 %bad_sum, %bad_named_a
  %bad2 = or i1 %bad1, %bad_named_b
  %bad3 = or i1 %bad2, %bad_mixed_real
  %bad4 = or i1 %bad3, %bad_mixed_integer
  %bad5 = or i1 %bad4, %bad_real
  %bad6 = or i1 %bad5, %bad_integer
  %bad7 = or i1 %bad6, %bad_hfa_a
  %bad8 = or i1 %bad7, %bad_hfa_b
  %result = zext i1 %bad8 to i32
  ret i32 %result
}

define i64 @managed_probe(ptr %obj) {
entry:
  %root = alloca ptr, align 8
  store ptr %obj, ptr %root, align 8
  call void @pcc_gc_frame_enter(ptr @frame_map, ptr %root)
  %before = load ptr, ptr %root, align 8
  %derived = getelementptr i8, ptr %before, i64 8
  %selected = getelementptr i8, ptr %derived, i64 0
  call void @pcc_thread_safepoint()
  %value = call i64 @peek(ptr %selected)
  call void @pcc_gc_frame_leave(ptr %root)
  ret i64 %value
}

define i32 @probe() {
entry:
  %initial = load i64, ptr @tls_init, align 8
  %zero = load i64, ptr @tls_zero, align 8
  store i64 43, ptr @tls_init, align 8
  store i64 17, ptr @tls_zero, align 8
  %moved = call i64 @managed_probe(ptr @old_storage)
  %changed = load i64, ptr @tls_init, align 8
  %changed_zero = load i64, ptr @tls_zero, align 8
  %bad_initial = icmp ne i64 %initial, 37
  %bad_zero = icmp ne i64 %zero, 0
  %bad_changed = icmp ne i64 %changed, 43
  %bad_changed_zero = icmp ne i64 %changed_zero, 17
  %bad_moved = icmp ne i64 %moved, 222
  %bad1 = or i1 %bad_initial, %bad_zero
  %bad2 = or i1 %bad1, %bad_changed
  %bad3 = or i1 %bad2, %bad_changed_zero
  %bad4 = or i1 %bad3, %bad_moved
  %result = zext i1 %bad4 to i32
  %status = shl i32 %result, 1
  ret i32 %status
}
'''

# The program object's initialized TLS comes first in link order and is
# aligned to eight bytes. The owned AArch64 ELF linker places its first TLS
# byte at TP + align_up(16, tls_align). Use the mapped template directly for
# this one-thread fixture; it deliberately does not replace runtime startup.
# The separately defined zero TLS value exercises external TLS metadata and
# initial-exec GOT relocations through the structured ELF projection.
_START = '''
.section __TEXT,__text,regular,pure_instructions
.p2align 2
.globl _start
_start:
  adrp x9, tls_init@PAGE
  add x9, x9, tls_init@PAGEOFF
  sub x9, x9, #16
  msr tpidr_el0, x9
  sub sp, sp, #48
  mov x0, #1
  mov x1, #2
  mov x2, #3
  mov x3, #4
  mov x4, #5
  mov x5, #6
  mov x6, #7
  mov x7, #99
  mov x9, #31
  str x9, [sp]
  mov x9, #32
  str x9, [sp, #8]
  adrp x9, fp_values@PAGE
  add x9, x9, fp_values@PAGEOFF
  ldr d0, [x9]
  ldr d1, [x9, #8]
  ldr d2, [x9, #16]
  ldr x10, [x9, #24]
  str x10, [sp, #16]
  mov x10, #42
  str x10, [sp, #24]
  mov x10, #61
  str x10, [sp, #32]
  bl collect
  add sp, sp, #48
  cbnz w0, L_exit
  bl probe
L_exit:
  mov x8, #93
  svc #0
  brk #0
.globl pcc_gc_frame_enter
pcc_gc_frame_enter:
  adrp x9, registered_root@PAGE
  add x9, x9, registered_root@PAGEOFF
  str x1, [x9]
  ret
.globl pcc_thread_safepoint
pcc_thread_safepoint:
  adrp x9, registered_root@PAGE
  add x9, x9, registered_root@PAGEOFF
  ldr x9, [x9]
  adrp x10, new_storage@PAGE
  add x10, x10, new_storage@PAGEOFF
  str x10, [x9]
  ret
.globl pcc_gc_frame_leave
pcc_gc_frame_leave:
  adrp x9, registered_root@PAGE
  add x9, x9, registered_root@PAGEOFF
  str xzr, [x9]
  ret
.globl peek
peek:
  ldr x0, [x0]
  ret
.section __DATA,__data
.p2align 3
registered_root:
  .quad 0
fp_values:
  .double 51.5, 71.5, 72.5, 41.5
.section __DATA,__thread_data,thread_local_regular
.p2align 3
.globl tls_zero
tls_zero:
  .quad 0
'''


def _forbidden(*args, **kwargs):
    raise AssertionError("unexpected external build or structured text round-trip")


@pytest.mark.integration
@pytest.mark.pcc_gate(
    unavailable=None if _LINUX_AARCH64 else "requires native Linux AArch64 execution",
)
def test_linux_aarch64_transport_executes_tls_varargs_and_managed_reload(
    tmp_path, monkeypatch,
):
    # Parse the exact same immutable IR independently for each producer.
    # Both compiler/assembler/linker routes are owned and run in process.
    with monkeypatch.context() as build:
        build.setattr(subprocess, "Popen", _forbidden)
        text = emit_aarch64_darwin_asm(_IR, optimize=False)
        expected = emit_relocatable(arm64_elf_driver.assemble_file(text))
        with monkeypatch.context() as direct:
            direct.setattr(arm64_asm_driver, "assemble_file", _forbidden)
            direct.setattr(arm64_asm_driver, "assemble_lines", _forbidden)
            direct.setattr(arm64_elf_driver, "assemble_file", _forbidden)
            direct.setattr(arm64_elf_driver, "assemble_sections", _forbidden)
            transport = emit_aarch64_darwin_indexed_transport(
                parse_self_backend_module(_IR),
                optimize=False,
                structured_instructions=True,
            )
            assert transport.native_finalized
            assert transport.encoded_line_records is None
            assert transport.line_chunks == []
            assert transport.fallback_instruction_count == 0
            assert transport.fallback_instruction_lines == ()
            assert transport.native_fragment_record_count > 0
            sections, undefined = transport.assemble_sections()
            actual = emit_relocatable(
                arm64_elf_driver.from_sections(sections, undefined),
            )
        assert actual == expected
        startup = arm64_elf_driver.assemble_file(_START)
        images = {}
        for route, encoded in (("structured", actual), ("text", expected)):
            obj = parse_relocatable(encoded)
            assert obj.machine == EM_AARCH64
            tls = next(symbol for symbol in obj.symbols if symbol.name == "tls_zero")
            assert tls.type == STT_TLS and tls.section_index == 0
            tls_index = obj.symbols.index(tls)
            assert {
                relocation.type
                for section in obj.sections
                for relocation in section.relocations
                if relocation.symbol_index == tls_index
            } == {541, 542}
            stackmaps = next(
                section for section in obj.sections
                if section.name == ".pcc_stackmaps"
            )
            maps = decode_stack_map(stackmaps.data, expected_arch=ARCH_AARCH64)
            managed = next(
                item for item in maps.functions
                if item.function_id == function_id("managed_probe")
            )
            assert any(
                record.kind == SAFEPOINT_CALL
                and any(
                    location.flags & LOCATION_MANAGED
                    for location in record.locations
                )
                for record in managed.records
            )
            image = link_static_executable([obj, startup])
            assert parse_static_executable(image)["tls_segments"] == 1
            images[route] = image

    (tmp_path / "program.ll").write_text(_IR, encoding="utf-8")
    (tmp_path / "program.s").write_text(text, encoding="utf-8")
    for route, image in images.items():
        executable = tmp_path / route
        executable.write_bytes(image)
        executable.chmod(0o755)
        result = subprocess.run([str(executable)], capture_output=True, timeout=10)
        assert (result.returncode, result.stdout, result.stderr) == (0, b"", b""), (
            route, result.returncode, result.stdout, result.stderr,
        )
